import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const copyToVault = process.argv.includes('--copy');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: copyToVault ? [{
		name: 'copy-to-vault',
		setup(build) {
			build.onEnd(async () => {
				try {
					await execAsync('node scripts/copy-to-vault.mjs');
				} catch (error) {
					console.error('Copy to vault failed:', error.message);
				}
			});
		},
	}] : [],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
